import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/UI/Navbar";
import Footer from "@/components/UI/Footer";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
         <Suspense fallback={<div>Loading...</div>}>
          <Navbar />
        </Suspense>
        <main className="pt-16">
          {" "}
          {/* Adjusted for fixed navbar */}
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
